### ISSUE TITLE
Decode error, no callbacks

### ISSUE THREAD

**Issue by tklengyel** [nyx-fuzz/libxdc#2]
Hey guys, so I'm running into an issue and I'm a bit stuck. I have a 64k PT buffer recorded by Xen and `ptdump` seems to be able to parse the buffer no problem.
```
00000000000010a0  psb
00000000000010b0  pad
00000000000010b1  pad
00000000000010b2  pad
00000000000010b3  mode.tsx
00000000000010b5  mode.exec  cs.l
00000000000010b7  fup        3: 00007f918d853264
00000000000010be  pad
00000000000010bf  pad
00000000000010c0  pad
00000000000010c1  pad
00000000000010c2  pad
00000000000010c3  pad
00000000000010c4  pad
00000000000010c5  pad
00000000000010c6  pip        b2619800, nr              cr3  00000000b2619800
00000000000010ce  pad
00000000000010cf  pad
00000000000010d0  pad
00000000000010d1  pad
00000000000010d2  pad
00000000000010d3  pad
00000000000010d4  pad
00000000000010d5  pad
00000000000010d6  vmcs       2b5b75000                 vmcs 00000002b5b75000
00000000000010dd  pad
00000000000010de  pad
00000000000010df  pad
00000000000010e0  pad
00000000000010e1  pad
00000000000010e2  pad
00000000000010e3  pad
00000000000010e4  pad
00000000000010e5  pad
00000000000010e6  tsc        412444672534
00000000000010ee  pad
00000000000010ef  pad
00000000000010f0  cbr        8
00000000000010f4  psbend
00000000000010f6  tnt.8      ..!.!.
:
```
I've enabled `DEBUG_TRACES` in `libxdc` but this is as far is gets:
```
PSB
MODE
MODE
FUP     7f918d853264 (TNT: 0)
VMCS
```

Afterwards `libxdc_decode` just returns with the value 4. I have the buffer saved to a file if that helps with debugging this further.

**Comment by eqv** [comment]
The problem seems to be '00000000000010e6  tsc        412444672534'.
As per readme, you should disable TSC package generation, as they produce unnecessary overhead.

**Comment by tklengyel** [comment]
Ah I see. `This decoder expects that return compression and generation of CYC, TSC and MTC packets are disabled.` Alright, I'll just tweak the Xen side to do that. Thanks! :)

**Comment by tklengyel** [comment]
With the correct bits set in the MSR it's confirmed to be working properly.
