### ISSUE TITLE
Can libxdc support to rebuild the Ptrix-type path coverage without disassemble?

### ISSUE THREAD

**Issue by MoonLight-SteinsGate** [nyx-fuzz/libxdc#20]
libxdc is a great work in the decoders of Intel PT, particularly in the hardware-assisted fuzzing. I notice that the evaluation in this repo shows that libxdc is faster than Ptrix, which rebuilds the coverage without disassemble. Though libxdc utilizes many micro-optimization to accelerate the process of rebuilding coverage, I'm interesting in whether libxdc will be faster in rebuilding the Ptrix-type path coverage without disassembly.

**Comment by eqv** [comment]
Not really. There is two obvious choices to make libxdc faster by avoiding disassembly:

1)  Just don't do disassembly - This is a decent candidate int theory. But every approach I've seen either only uses TIP packets (you loose like 98% of the edges) and / or leads to massive amounts of noise during fuzzing. Both of which will cost you a LOT more than the 3% perf you might gain in theory from avoiding disassembly. (In addition to being poorly implemented and overall slower in practice).

2) Build disassembly datastructures ahead of time (like killerbee). Libxdc just builds a similar Datastructure life as needed by the fuzzer. Doing this in preprocessing will make everything more complex, not work with code that only appears at runtime (e.g. .dll/.so being loaded), won't work with indirect branches etc.
