### ISSUE TITLE
Low stability reported by AFL

### ISSUE THREAD

**Issue by tklengyel** [nyx-fuzz/libxdc#6]
While using libxdc to gather the basic-block information AFL reports low stability score. Currently I register a bb callback and feed the `dst` address received in that function to AFL as a location that was instrumented. Stability seems to be howering around ~18%. In my setup interrupts are blocked and the code being fuzzed is tiny with no external calls. The low stability score only pops up while using PT+libxdc, breakpoint based tracing yields stability in the ~95% range.

**Comment by eqv** [comment]
You can't use the bb callback for that. First of all the BB callback doesn't really have a src and dst address, and secondly it will only be triggered once after the bb was disassembled. After that, the bb will be taken from the cache, and no more callbacks will be issued (which obviously will cause low stability). If you absolutely need to do this, please use the edge callback. But we heavily recommend to use these functions only for debugging purposes, as the mechanism we use internally will be significantly faster (at least some 2x).

**Comment by tklengyel** [comment]
OK, so I tried using the AFL map as the bitmap directly and I was resetting that between runs. But low stability still.

**Comment by eqv** [comment]
Can pick one of the inputs from the queue, and dump the trace data a few times? Maybe install a trace hook that prints each edge taken,  and see if the edges look sane. If you dump the traces, you can use the intel decoder to create a ground truth for the edges taken, and have a look at where they diverge.

**Comment by tklengyel** [comment]
This might have been due to me only partially resetting the bitmap that AFL sends after each iteration. With that getting memset completely to 0 for each iteration I get 100% stability with breakpoint based tracing, ~60% stability with PT. Still not sure why it's lower with this method though, it should be also close to 100%.

**Comment by eqv** [comment]
Well that's a step in the right direction. If you dump some of the traces, we can figure out if the problem is within libxdc or if there is something else happening that's causing the nondeterminism outside of libxdc.

**Comment by tklengyel** [comment]
Ah, I think I know what's wrong. When I'm resetting the forks I thought I've moved back the PT output_mask buffer's starting point to 0, but I suspect it wasn't actually doing it because I never updated the MSR (thought it will pick up the value on VMENTRY). So we were actually only picking up new coverage trace information when the buffer wrapped, which also explains why it took a while before all paths were seen with PT based coverage :)
