### ISSUE TITLE
Support Visual Studio compiler?

### ISSUE THREAD

**Issue by BlackLuny** [nyx-fuzz/libxdc#9]
I want to try this as a static library on Windows.My project is a VS project with libipt static library.I want to try libxdc to get better performance.How can i do?Thks.

**Comment by eqv** [comment]
Neither of us uses Windows. You will have to take a look at the Makefile (https://github.com/nyx-fuzz/libxdc/blob/master/Makefile) and adapt it to visual studio. However the build process for the library is pretty straightforward: 
compile `cfg.o disassembler.o tnt_cache.o decoder.o libxdc.o mmh3.o trace_cache.o` and link all of them together with libcapstone4 to create the shared object. It should be noted that the default driver for intel-pt does enable return compression, which we do not support. So you will need to change that too, if you plan to use libxdc under windows.
